[CONFIG]
ErrorFile=sqliosim.log.xml
;CPUCount=2
;Affinity=0
;IOAffinity=0
;MaxMemoryMB=209
StopOnError=TRUE
TestCycles=1
TestCycleDuration=300
CacheHitRatio=10000
NoBuffering=TRUE
WriteThrough=TRUE
MaxOutstandingIO=0
TargetIODuration=100
AllowIOBursts=TRUE
UseScatterGather=TRUE
ForceReadAhead=FALSE
DeleteFilesAtStartup=TRUE
DeleteFilesAtShutdown=FALSE
StampFiles=FALSE

[RandomUser]
UserCount=0
JumpToNewRegionPercentage=500
MinIOChainLength=50
MaxIOChainLength=100
RandomUserReadWriteRatio=9000
MinLogPerBuffer=64
MaxLogPerBuffer=8192
RollbackChance=100
SleepAfter=5
YieldPercentage=0
CPUSimulation=FALSE
CPUCyclesMin=0
CPUCyclesMax=0

[AuditUser]
UserCount=0
BuffersValidated=64
DelayAfterCycles=2
AuditDelay=200

[ReadAheadUser]
UserCount=0
BuffersRAMin=32
BuffersRAMax=64
DelayAfterCycles=2
RADelay=200

[BulkUpdateUser]
;UserCount=4
BuffersBUMin=600
BuffersBUMax=1000
DelayAfterCycles=2
BUDelay=1

[ShrinkUser]
MinShrinkInterval=120
MaxShrinkInterval=600
MinExtends=1
MaxExtends=20

;[File1]
;FileName=f:\sqliosim.mdx
;InitialSize=100
;MaxSize=100
;Increment=10
;Shrinkable=FALSE
;LogFile=FALSE
;Sparse=FALSE

;[File2]
;FileName=f:\sqliosim.ldx
;InitialSize=50
;MaxSize=50
;Increment=0
;Shrinkable=FALSE
;LogFile=TRUE
;Sparse=FALSE

